# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
defaults: &defaults
  docker:
    # Use custom docker
    - image: juampynr/drupal8ci:latest
    # Mysql
    - image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: drupal8_circleci
        MYSQL_ROOT_PASSWORD: sentius
  working_directory: /var/www/html
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      #- run: 
          name: Composer install
          command: composer install --dev
      #- run:
          name: Install Drupal site 
          command: vendor/drupal/console/bin/drupal site:install  standard --account-name="admin" --site-mail="admin@example.com" --site-name="drupal8" --db-name="drupal8_circleci" --db-user="root" --db-pass="sentius" --no-interaction
      - run:
          name: Access Matbao hosting & go to iphonebacgiang.com directory
          command: ssh 125.253.113.81 -l tan && cd /var/www/html/iphonebacgiang.com
  test:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Composer install
          command: composer install --dev
      - run:
          name: Set install paths for coder_sniffer 
          command: vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
      - run: vendor/bin/phpcs --standard=Drupal web/core/modules/node/node.module
      - run: echo "Hello Tan Tan"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
