# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Use custom docker
      - image: juampynr/drupal8ci:latest
      # Mysql
      - image: mysql:latest
        restart: always
        environment:
          MYSQL_DATABASE: drupal8_circleci
          MYSQL_ROOT_PASSWORD: sentius
    working_directory: /var/www/html
    steps:
      - checkout
      - run: 
          name: Composer install
          command: composer install --dev
      - run:
          name: Install Drupal site 
          command: vendor/drupal/console/bin/drupal site:install  standard --account-name="admin" --site-mail="admin@example.com" --site-name="drupal8" --db-name="drupal8_circleci" --db-user="root" --db-pass="sentius" --no-interaction
      - run:
          name: Set install paths for coder_sniffer 
          command: vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  test:
    docker:
      # Use custom docker
      - image: juampynr/drupal8ci:latest
    steps:
      - checkout
      - run: vendor/bin/phpcs --standard=Drupal web/core/modules/node/node.module
      - run: echo "Hello Tan Tan"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
